"""Created by JXP and Claude.

B7: download the instrument / Keck / other images for the WMKO 2026 talk and
write presentations/2026_WMKO/figs/images/credits.md (URL, credit line,
license / usage terms) for each.

Wikimedia files: license and author are read from the file's own
extmetadata via the MediaWiki API at run time, so credits.md reflects what
the file page says. Non-Wikimedia files carry hand-entered terms below.

Usage:
    conda run -n ocean14 python presentations/py/fetch_images.py
"""
import html
import json
import re
import urllib.parse
import urllib.request

from slide_style import FIGS

OUT = FIGS / "images"
UA = {"User-Agent": "ClimateIntelligence-slides/1.0 (jxp@ucsc.edu)"}

# (local name, slide, what, source kind, title-or-URL, (credit, terms) for non-wiki)
IMAGES = [
    ("mauna_loa_observatory.jpg", "C1", "NOAA Mauna Loa Observatory",
     "commons", "File:Mauna Loa Observatory north flank of Mauna Loa.jpg", None),
    ("ceres_instrument.jpg", "C3a", "CERES instruments (flight models FM1/FM2)",
     "commons", "File:CERES FM1 FM2.jpeg", None),
    ("argo_float.jpg", "C4b", "Argo float deployed from a research vessel",
     "commons", "File:Argo float deployed from research vessel.jpg", None),
    ("sentinel6.jpg", "C6a", "Sentinel-6 Michael Freilich altimetry satellite",
     "commons", "File:Sentinel-6 Michael Freilich (2).jpg", None),
    ("honolulu_tide_station.jpg", "C6b", "NOAA tide station 1612340, Honolulu Harbor",
     "url", "https://tidesandcurrents.noaa.gov/images/stationphotos/1612340A.jpg",
     ("NOAA CO-OPS", "U.S. Government work, public domain.")),
    ("keck_primary.jpg", "A7", "Keck telescope segmented primary mirror",
     "commons", "File:Primary Mirror of Keck Telescope.jpg", None),
    ("hires.jpg", "A7", "HIRES spectrometer, Keck I",
     "url", "https://keckobservatory.org/wp-content/uploads/2023/09/HIRES-2048x1371-1.jpeg",
     ("Courtesy W. M. Keck Observatory", "WMKO image-use policy "
     "(https://www2.keck.hawaii.edu/gallery/copyright.php): educational use with credit; the newer "
     "keckobservatory.org gallery asks for written consent — fine for an internal WMKO staff talk, "
     "ask WMKO before any public posting.")),
    # A10: no usable film still of the Eye is freely available (en.wikipedia's non-free
    # File:Sauron.jpg shows the figure, not the Eye, at 352x199; Commons' "Sauron
    # replica" is also the figure). Placeholder: the astronomers' "Eye of Sauron";
    # the author decides (Q&A, Build questions).
    ("eye_of_sauron_ngc4151.jpg", "A10", "NGC 4151, the 'Eye of Sauron' galaxy (X-ray + optical)",
     "commons", 'File:NGC 4151- An Active Black Hole in the "Eye of Sauron" (2011-n4151 - n4151 1680).jpg', None),
]


def get_json(api, params):
    """Created by JXP and Claude. GET a MediaWiki API query and parse JSON."""
    url = api + "?" + urllib.parse.urlencode(params)
    return json.load(urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60))


def strip_tags(s):
    """Created by JXP and Claude. Remove HTML tags/entities from metadata."""
    return html.unescape(re.sub(r"<[^>]+>", "", s or "")).strip()


def wiki_info(api, title):
    """Created by JXP and Claude. Output: (download URL, page URL, artist,
    license short name, license URL) for a file title."""
    d = get_json(api, {"action": "query", "format": "json", "titles": title,
                       "prop": "imageinfo", "iiprop": "url|extmetadata"})
    page = next(iter(d["query"]["pages"].values()))
    ii = page["imageinfo"][0]
    m = ii.get("extmetadata", {})
    g = lambda k: strip_tags(m.get(k, {}).get("value", ""))
    return ii["url"], ii["descriptionurl"], g("Artist"), g("LicenseShortName"), g("LicenseUrl")


def download(url, path):
    """Created by JXP and Claude. Save url to path."""
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=120) as r:
        path.write_bytes(r.read())


def main():
    """Created by JXP and Claude. Fetch every image and write credits.md."""
    OUT.mkdir(parents=True, exist_ok=True)
    lines = ["# Image credits — WMKO 2026 talk", "",
             "Generated by `presentations/py/fetch_images.py`. Wikimedia licenses are read from each "
             "file page at download time.", "",
             "| File | Slide | What | Credit line for the slide | License / terms | Source |",
             "|---|---|---|---|---|---|"]
    for name, slide, what, kind, ref, terms in IMAGES:
        if kind == "commons":
            url, page, artist, lic, lic_url = wiki_info("https://commons.wikimedia.org/w/api.php", ref)
            credit = f"{artist} / Wikimedia Commons"
            terms = terms or (f"{lic}" + (f" ({lic_url})" if lic_url else ""))
            source = page
        else:
            url, source = ref, ref
            credit, terms = terms
        download(url, OUT / name)
        print(f"{name}: {(OUT / name).stat().st_size / 1e3:.0f} kB  [{terms[:60]}]")
        lines.append(f"| `{name}` | {slide} | {what} | {credit} | {terms} | {source} |")
    lines += ["", "`../../sacbee.png` (A1): screenshot of the author's own Sacramento Bee op-ed "
              "(21 Aug 2026), supplied by the author; used as-is (Q36). Hero photo in it: Dado Ruvic/Reuters."]
    (OUT / "credits.md").write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT / 'credits.md'}")


if __name__ == "__main__":
    main()
